name: Docker Image CI

on:
  push:
    branches: [ main, feature/Docker ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Setup JFrog CLI
      run: |
          curl -fL https://getcli.jfrog.io | sh
          chmod +x jfrog

    #- name: Configure the JFrog CLI
    #  run: |
    #      ./jfrog config add ${{secrets. JF_ARTIFACTORY_SECRET}}

    - name: Build Docker-Image
      run: |
        docker login luistorrescisneros.jfrog.io -u ${{ secrets.JF_ARTIFACTORY_USER}} -p ${{ secrets.JF_ARTIFACTORY_PASSWORD}}
        docker build --tag luistorrescisneros.jfrog.io/docker-aws-runner-linux-local/my-docker-image:${{ github.run_number }} -f docker/Dockerfile .
    
    # Push to JFrog Registry
    - name: Push Docker-Image
      run: |
        docker push luistorrescisneros.jfrog.io/docker-aws-runner-linux-local/my-docker-image:${{ github.run_number }}