name: Docker Image CI

on:
  push:
    branches: [ main, feature/Docker ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Setup JFrog CLI
      run: |
          curl -fL https://getcli.jfrog.io | sh
          chmod +x jfrog

    #- name: Configure the JFrog CLI
    #  run: |
    #      ./jfrog config add ${{secrets. JF_ARTIFACTORY_SECRET}}

    - name: Build the docker images
      run: |
          docker login luistorrescisneros.jfrog.io -u ${{ secrets.JF_ARTIFACTORY_USER}} -p ${{ secrets.JF_ARTIFACTORY_PASSWORD}}
          docker build --tag luistorrescisneros.jfrog.io/docker/my-docker-image:latest .