name: Docker Image CI

on:
  push:
    branches: [ main, feature/Docker ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    env:
      tag: ${{ github.run_id }}

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    # Build Docker-Image within self-hosted runner
    - name: Build Docker-Image
      run: |
        docker build --tag luistorrescisneros.jfrog.io/docker-aws-runner-linux-local/my-docker-image:${{ env.tag }} -f docker/Dockerfile .
    
    # Push to Docker-JFrog Registry
    - name: Push Docker-Image
      run: |
        docker login luistorrescisneros.jfrog.io -u ${{ secrets.JF_ARTIFACTORY_USER}} -p ${{ secrets.JF_ARTIFACTORY_PASSWORD}}
        docker push luistorrescisneros.jfrog.io/docker-aws-runner-linux-local/my-docker-image:${{ env.tag }}

    # Run Docker-Image on self-hosted runner
    - name: Run Docker-Image (Print tests results)
      run: |
        docker run --rm --cpus="1.0" luistorrescisneros.jfrog.io/docker-aws-runner-linux-local/my-docker-image:${{ env.tag }}  