name: Docker Image CI

on:
  push:
    branches: [ main, feature/Docker ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Setup JFrog CLI
      run: |
          curl -fL https://getcli.jfrog.io | sh
          chmod +x jfrog

    - name: Configure the CLI
      run: |
        ./jfrog config add import ${{secrets. JF_ARTIFACTORY_SECRET}}
