name: Docker Image CI

on:
  push:
    branches: [ main, feature/Docker ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    # Build Docker-Image within self-hosted runner
    - name: Build Docker-Image
      run: |
        docker build --tag luistorrescisneros.jfrog.io/docker-aws-runner-linux-local/my-docker-image:${{ github.run_number }} -f docker/Dockerfile .
    
    # Push to Docker-JFrog Registry
    - name: Push Docker-Image
      run: |
        docker login luistorrescisneros.jfrog.io -u ${{ secrets.JF_ARTIFACTORY_USER}} -p ${{ secrets.JF_ARTIFACTORY_PASSWORD}}
        docker push luistorrescisneros.jfrog.io/docker-aws-runner-linux-local/my-docker-image:${{ github.run_number }}

    # Run Docker-Image on self-hosted runner
    - name: Run Docker-Image (Print tests results)
      run: |
        docker run --rm luistorrescisneros.jfrog.io/docker-aws-runner-linux-local/my-docker-image:${{ github.run_number }}  